import java.net.URL;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.Mixer;
//
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.PrintStream;

import java.lang.reflect.Array;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.++
 */

/**
 *
 * @author yadfani
 */
public class Consol extends javax.swing.JFrame {

    /**
     * Creates new form Consol
     */
    public static Mixer mixer;
    public static Clip clip1;
    public static Clip clip2;
    public static Clip clip3;
    public static Clip clip4;
    Secuenciador sc = new Secuenciador();

    //Secuenciador sc = new Secuenciador();
    public Consol() {
        //sc.porDefecto();
        initComponents();
        Mixer.Info[] mixInfos = AudioSystem.getMixerInfo();
        //Indicamos la salida que queremos usar
        mixer = AudioSystem.getMixer(mixInfos[0]);
        //Indicamos que vamos a usar un archivo dentri de nuestra
        //Clase
        DataLine.Info dataInfo = new DataLine.Info(Clip.class,null);

        try{
            //Indicando de dónde se reproduce el clip
            clip1 = (Clip)mixer.getLine(dataInfo);
            clip2 = (Clip)mixer.getLine(dataInfo);
            clip3 = (Clip)mixer.getLine(dataInfo);
            clip4 = (Clip)mixer.getLine(dataInfo);
        }catch(Exception e){

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JToggleButton();
        btn2 = new javax.swing.JToggleButton();
        btn3 = new javax.swing.JToggleButton();
        btn4 = new javax.swing.JToggleButton();
        btn5 = new javax.swing.JToggleButton();
        btn6 = new javax.swing.JToggleButton();
        btn7 = new javax.swing.JToggleButton();
        btn8 = new javax.swing.JToggleButton();
        btn9 = new javax.swing.JToggleButton();
        btn10 = new javax.swing.JToggleButton();
        btn11 = new javax.swing.JToggleButton();
        btn12 = new javax.swing.JToggleButton();
        btn13 = new javax.swing.JToggleButton();
        btn14 = new javax.swing.JToggleButton();
        btn15 = new javax.swing.JToggleButton();
        btn16 = new javax.swing.JToggleButton();
        btn17 = new javax.swing.JToggleButton();
        btn18 = new javax.swing.JToggleButton();
        btn19 = new javax.swing.JToggleButton();
        btn20 = new javax.swing.JToggleButton();
        btn21 = new javax.swing.JToggleButton();
        btn22 = new javax.swing.JToggleButton();
        btn23 = new javax.swing.JToggleButton();
        btn24 = new javax.swing.JToggleButton();
        btn25 = new javax.swing.JToggleButton();
        btn26 = new javax.swing.JToggleButton();
        btn27 = new javax.swing.JToggleButton();
        btn28 = new javax.swing.JToggleButton();
        btn29 = new javax.swing.JToggleButton();
        btn30 = new javax.swing.JToggleButton();
        btn31 = new javax.swing.JToggleButton();
        btn32 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        textSpeed = new javax.swing.JTextField();
        btnPlay = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        textRepeat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        btn1.setBackground(new java.awt.Color(204, 102, 255));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 102, 153));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 153, 255));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 204, 204));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(204, 102, 255));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(255, 102, 153));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(255, 153, 255));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(255, 204, 204));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(204, 102, 255));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn10.setBackground(new java.awt.Color(255, 102, 153));
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn11.setBackground(new java.awt.Color(255, 153, 255));
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn12.setBackground(new java.awt.Color(255, 204, 204));
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn13.setBackground(new java.awt.Color(204, 102, 255));
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn14.setBackground(new java.awt.Color(255, 102, 153));
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });

        btn15.setBackground(new java.awt.Color(255, 153, 255));
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });

        btn16.setBackground(new java.awt.Color(255, 204, 204));
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });

        btn17.setBackground(new java.awt.Color(204, 102, 255));
        btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn17ActionPerformed(evt);
            }
        });

        btn18.setBackground(new java.awt.Color(255, 102, 153));
        btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn18ActionPerformed(evt);
            }
        });

        btn19.setBackground(new java.awt.Color(255, 153, 255));
        btn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn19ActionPerformed(evt);
            }
        });

        btn20.setBackground(new java.awt.Color(255, 204, 204));
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        btn21.setBackground(new java.awt.Color(204, 102, 255));
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });

        btn22.setBackground(new java.awt.Color(255, 102, 153));
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });

        btn23.setBackground(new java.awt.Color(255, 153, 255));
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });

        btn24.setBackground(new java.awt.Color(255, 204, 204));
        btn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24ActionPerformed(evt);
            }
        });

        btn25.setBackground(new java.awt.Color(204, 102, 255));
        btn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn25ActionPerformed(evt);
            }
        });

        btn26.setBackground(new java.awt.Color(255, 102, 153));
        btn26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn26ActionPerformed(evt);
            }
        });

        btn27.setBackground(new java.awt.Color(255, 153, 255));
        btn27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn27ActionPerformed(evt);
            }
        });

        btn28.setBackground(new java.awt.Color(255, 204, 204));
        btn28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn28ActionPerformed(evt);
            }
        });

        btn29.setBackground(new java.awt.Color(204, 102, 255));
        btn29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn29ActionPerformed(evt);
            }
        });

        btn30.setBackground(new java.awt.Color(255, 102, 153));
        btn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30ActionPerformed(evt);
            }
        });

        btn31.setBackground(new java.awt.Color(255, 153, 255));
        btn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn31ActionPerformed(evt);
            }
        });

        btn32.setBackground(new java.awt.Color(255, 204, 204));
        btn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn32ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fish.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boat.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sea.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(70, 70, 70))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Caracol.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(51, 255, 51));

        textSpeed.setText("velocidad");
        textSpeed.setToolTipText("");
        textSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSpeedActionPerformed(evt);
            }
        });

        btnPlay.setBackground(new java.awt.Color(0, 153, 102));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-reproducir-en-círculo-30.png"))); // NOI18N
        btnPlay.setMinimumSize(new java.awt.Dimension(545, 521));
        btnPlay.setPreferredSize(new java.awt.Dimension(50, 50));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(153, 0, 0));
        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-detener-en-círculos-30.png"))); // NOI18N
        btnStop.setPreferredSize(new java.awt.Dimension(50, 50));
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        textRepeat.setText("repeticiones");
        textRepeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRepeatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textRepeat)
                    .addComponent(textSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(textSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sunny_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn24, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn25, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn26, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn27, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn28, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn29, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn30, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn29, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn30, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn25, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn26, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn27, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn28, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn24, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn32ActionPerformed
        // TODO add your handling code here:
        if(btn32.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4Pool.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(7, true);
            System.out.println("Seleccionado" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin4.set(7,false);
            System.out.println("No selec" + sc.lin4.toString());
        }
    }//GEN-LAST:event_btn32ActionPerformed

    private void btn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn31ActionPerformed
        // TODO add your handling code here:
        if(btn31.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3Wave.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(7, true);
            System.out.println("Seleccionado" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin3.set(7,false);
            System.out.println("No selec" + sc.lin3.toString());
        }
    }//GEN-LAST:event_btn31ActionPerformed

    private void btn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30ActionPerformed
        // TODO add your handling code here:
        if(btn30.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2Whale.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(7, true);
            System.out.println("Seleccionado" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin2.set(7,false);
            System.out.println("No selec" + sc.lin2.toString());
        }
    }//GEN-LAST:event_btn30ActionPerformed

    private void btn29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn29ActionPerformed
        // TODO add your handling code here:
        if(btn29.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1Bubble.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(7, true);
            System.out.println("Seleccionado" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin1.set(7,false);
            System.out.println("No selec" + sc.lin1.toString());
        }
    }//GEN-LAST:event_btn29ActionPerformed

    private void btn28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn28ActionPerformed
        // TODO add your handling code here:
        if(btn28.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4Pool.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(6, true);
            System.out.println("Seleccionado" + sc.lin4.toString());
            clip4.open(audioStream); 
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin4.set(6,false);
            System.out.println("No selec" + sc.lin4.toString());
        }
    }//GEN-LAST:event_btn28ActionPerformed

    private void btn27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn27ActionPerformed
        // TODO add your handling code here:
        if(btn27.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3Wave.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(6, true);
            System.out.println("Seleccionado" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin3.set(6,false);
            System.out.println("No selec" + sc.lin3.toString());
        }
    }//GEN-LAST:event_btn27ActionPerformed

    private void btn26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn26ActionPerformed
        // TODO add your handling code here:
        if(btn26.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2Whale.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(6, true);
            System.out.println("Seleccionado" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin2.set(6,false);
            System.out.println("No selec" + sc.lin2.toString());
        }
    }//GEN-LAST:event_btn26ActionPerformed

    private void btn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn25ActionPerformed
        // TODO add your handling code here:
        if(btn25.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1Bubble.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(6, true);
            System.out.println("Seleccionado" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin1.set(6,false);
            System.out.println("No selec" + sc.lin1.toString());
        }
    }//GEN-LAST:event_btn25ActionPerformed

    private void btn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn24ActionPerformed
        // TODO add your handling code here:
        if(btn24.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4Pool.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(5, true);
            System.out.println("Seleccionado" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin4.set(5,false);
            System.out.println("No selec" + sc.lin4.toString());
        }
    }//GEN-LAST:event_btn24ActionPerformed

    private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn23ActionPerformed
        // TODO add your handling code here:
        if(btn23.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3Wave.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(5, true);
            System.out.println("Seleccionado" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin3.set(5,false);
            System.out.println("No selec" + sc.lin3.toString());
        }
    }//GEN-LAST:event_btn23ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        // TODO add your handling code here:
        if(btn22.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2Whale.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(5, true);
            System.out.println("Seleccionado" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin2.set(5,false);
            System.out.println("No selec" + sc.lin2.toString());
        }
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        // TODO add your handling code here:
        if(btn21.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1Bubble.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(5, true);
            System.out.println("Seleccionado" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin1.set(5,false);
            System.out.println("No selec" + sc.lin1.toString());
        }
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
        if(btn20.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4Pool.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(4, true);
            System.out.println("Seleccionado" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin4.set(4,false);
            System.out.println("No selec" + sc.lin4.toString());
        }
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn19ActionPerformed
        // TODO add your handling code here:
        if(btn19.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3Wave.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(4, true);
            System.out.println("Seleccionado" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin3.set(4,false);
            System.out.println("No selec" + sc.lin3.toString());
        }
    }//GEN-LAST:event_btn19ActionPerformed

    private void btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn18ActionPerformed
        // TODO add your handling code here:
        if(btn18.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2Whale.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(4, true);
            System.out.println("Seleccionado" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin2.set(4,false);
            System.out.println("No selec" + sc.lin2.toString());
        }
    }//GEN-LAST:event_btn18ActionPerformed

    private void btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn17ActionPerformed
        // TODO add your handling code here:
        if(btn17.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1Bubble.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(4, true);
            System.out.println("Seleccionado" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin1.set(4,false);
            System.out.println("No selec" + sc.lin1.toString());
        }
    }//GEN-LAST:event_btn17ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        // TODO add your handling code here:
        if(btn16.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4Pool.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(3, true);
            System.out.println("Seleccionado" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin4.set(3,false);
            System.out.println("No selec" + sc.lin4.toString());
        }
    }//GEN-LAST:event_btn16ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        // TODO add your handling code here:
        if(btn15.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3Wave.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(3, true);
            System.out.println("Seleccionado" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin3.set(3,false);
            System.out.println("No selec" + sc.lin3.toString());
        }
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        // TODO add your handling code here:
        if(btn14.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2Whale.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(3, true);
            System.out.println("Seleccionado" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin2.set(3,false);
            System.out.println("No selec" + sc.lin2.toString());
        }
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        // TODO add your handling code here:
        if(btn13.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1Bubble.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(3, true);
            System.out.println("Seleccionado" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin1.set(3,false);
            System.out.println("No selec" + sc.lin1.toString());
        }
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
        if(btn12.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4Pool.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(2, true);
            System.out.println("Seleccionado" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin4.set(2,false);
            System.out.println("No selec" + sc.lin4.toString());
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        if(btn11.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3Wave.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(2, true);
            System.out.println("Seleccionado" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin3.set(2,false);
            System.out.println("No selec" + sc.lin3.toString());
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        if(btn10.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2Whale.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(2, true);
            System.out.println("Seleccionado" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin2.set(2,false);
            System.out.println("No selec" + sc.lin2.toString());
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if(btn9.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1Bubble.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(2, true);
            System.out.println("Seleccionado" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin1.set(2,false);
            System.out.println("No selec" + sc.lin1.toString());
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if(btn8.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4Pool.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(1, true);
            System.out.println("Seleccionado" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin4.set(1,false);
            System.out.println("No selec" + sc.lin4.toString());
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if(btn7.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3Wave.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(1, true);
            System.out.println("Seleccionado" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin3.set(1,false);
            System.out.println("No selec" + sc.lin3.toString());
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if(btn6.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2Whale.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(1, true);
            System.out.println("Seleccionado" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin2.set(1,false);
            System.out.println("No selec" + sc.lin2.toString());
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if(btn5.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1Bubble.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(1, true);
            System.out.println("Seleccionado" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin1.set(1,false);
            System.out.println("No selec" + sc.lin1.toString());
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:

        if(btn4.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4Pool.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(0, true);
            System.out.println("Seleccionado" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin4.set(0,false);
            System.out.println("No selec" + sc.lin4.toString());
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        //sc.lin3.set(0) = true;
        if(btn3.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3bobmbo.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(0, true);
            System.out.println("Seleccionado" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin3.set(0,false);
            System.out.println("No selec" + sc.lin3.toString());
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if(btn2.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2Whale.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(0, true);
            System.out.println("Seleccionado" + sc.lin1.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin1.set(0,false);
            System.out.println("No selec" + sc.lin1.toString());
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if(btn1.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1Bubble.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(0, true);
            System.out.println("Seleccionado" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        //Clip.LOOP_CONTINUOUSLY
        }else{
            sc.lin1.set(0,false);
            System.out.println("No selec" + sc.lin1.toString());
        }

    }//GEN-LAST:event_btn1ActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        String texto = textRepeat.getText();
        if(texto.equals("loop")){
            sc.loop = true;
            sc.bpm = (int) 60000 / Integer.parseInt(textSpeed.getText());
        }else{
           sc.repeat = Integer.parseInt(texto);
           sc.loop = false;
           sc.bpm = (int) 60000/Integer.parseInt(textSpeed.getText());
        }
        System.out.println(texto);
        try{
            //Socket parar = new Socket("192.168.1.10",9998);
            Socket paquete_enviar = new Socket("192.168.56.1",9999);

            
            //PrintStream salida = new PrintStream(parar.getOutputStream());
            //asalida.println("false");
            //Secuenciador salida = new Secuenciador();
            ObjectOutputStream paquete_salida = new ObjectOutputStream(paquete_enviar.getOutputStream());
            paquete_salida.writeObject(sc);
            paquete_enviar.close();

            
        }catch(Exception e){
            
        }
        
        /*switch(texto){
            case "loop":
                try{
                    URL soundURL = Consol.class.getResource("tarola.wav");
                    AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
                    clip1.open(audioStream);
                }catch(Exception e){

                }
                clip1.loop(Clip.LOOP_CONTINUOUSLY);
                break;
        }*//* El switch se sustituira por un arreglo que se enviará al socket y también se
        enviará el texto, el clip.loop se implementará en el cpu2 */

    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        try {
            // TODO add your handling code here:
            Socket paquete_enviar = new Socket("192.168.56.1",9998);
            ObjectOutputStream paquete_salida = new ObjectOutputStream(paquete_enviar.getOutputStream());
            paquete_salida.writeObject(new Detenerc());
            paquete_enviar.close();
        } catch (IOException ex) {
            Logger.getLogger(Consol.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStopActionPerformed

    private void textSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSpeedActionPerformed

    private void textRepeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRepeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRepeatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws UnknownHostException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn1;
    private javax.swing.JToggleButton btn10;
    private javax.swing.JToggleButton btn11;
    private javax.swing.JToggleButton btn12;
    private javax.swing.JToggleButton btn13;
    private javax.swing.JToggleButton btn14;
    private javax.swing.JToggleButton btn15;
    private javax.swing.JToggleButton btn16;
    private javax.swing.JToggleButton btn17;
    private javax.swing.JToggleButton btn18;
    private javax.swing.JToggleButton btn19;
    private javax.swing.JToggleButton btn2;
    private javax.swing.JToggleButton btn20;
    private javax.swing.JToggleButton btn21;
    private javax.swing.JToggleButton btn22;
    private javax.swing.JToggleButton btn23;
    private javax.swing.JToggleButton btn24;
    private javax.swing.JToggleButton btn25;
    private javax.swing.JToggleButton btn26;
    private javax.swing.JToggleButton btn27;
    private javax.swing.JToggleButton btn28;
    private javax.swing.JToggleButton btn29;
    private javax.swing.JToggleButton btn3;
    private javax.swing.JToggleButton btn30;
    private javax.swing.JToggleButton btn31;
    private javax.swing.JToggleButton btn32;
    private javax.swing.JToggleButton btn4;
    private javax.swing.JToggleButton btn5;
    private javax.swing.JToggleButton btn6;
    private javax.swing.JToggleButton btn7;
    private javax.swing.JToggleButton btn8;
    private javax.swing.JToggleButton btn9;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField textRepeat;
    private javax.swing.JTextField textSpeed;
    // End of variables declaration//GEN-END:variables
}
